dennisvang/tufup

- .readthedocs.yaml
- docs/Makefile
- docs/make.bat
- docs/requirements.txt
- docs/source/api.rst
- docs/source/conf.py
- docs/source/index.rst
- docs/source/robots.txt
- requirements.txt
This sets up sphinx, and ReadTheDocs so we can generate documentation, guides and tutorials in the future.
* Example can be [seen here](https://notsotuf.readthedocs.io/en/latest/)
* I'll take the documentation (on the above link from my fork down) once @dennisvang  signs up to rtd and enables the original project
More pages should of course be added in the future, like an installation and getting started page.
But this provides all the boilerplate and configuration
fixes #1
> Initial documentation framework

- src/tufup/client.py
- tests/test_client.py
It turns out python-tuf #2047 is not a bug after all, but rather a misconfiguration on the server-side:
The issue arises if the server sends a `Content-Encoding: gzip` header when it should *not* do so.
fixes #26
> undo workaround

- README.md
- src/tufup/client.py
- src/tufup/utils/platform_specific.py
- tests/test_utils_platform_specific.py
Our initial implementation of the windows install script uses the `robocopy /purge` option by default, same as the corresponding `pyupdater` implementation.
However, this may lead to inadvertent deletion of unrelated files and folders, if users do not run their application from a dedicated directory, as described in issue #38.
To prevent inadvertent data loss, we will make the purge optional. This is a major change in behavior on the client side.
Changes:
- add new optional arguments to `install_update()` and implement optional purge, both for windows and macos: 
- `purge_dst_dir` (default: `False`)
- `exclude_from_purge` (default: `None`)
- replace `extra_robocopy_options` argument for windows by `robocopy_options_override`
- add more explicit warnings to readme and docstrings
> Issue38: optional purge

- src/tufup/utils/platform_specific.py
- tests/test_utils_platform_specific.py
Default windows install script is modified so output and errors are redirected to a log file.
The optional `debug` argument is replaced by an optional `log_file_name` argument.
> Add option to create install log file (Windows)

- pyproject.toml
- requirements.txt
- setup.cfg
- tests/test_package.py
Fixes #44 
- bumped tuf version in setup.cfg
- bumped setuptools version
Install dependencies from setup.cfg using `pip install .` (from project root directory), then freeze into requirements.txt
Note that we use a function from `setuptools` on the repo side, but `setuptools` is considered special, so it is excluded from the `pip freeze` output... See e.g. this interesting discussion: https://github.com/pypa/pipenv/issues/1417
> Fix issue 44: tuf dependency

- src/tufup/utils/platform_specific.py
- tests/test_utils_platform_specific.py
fixes #47 
In addition to the existing `install` function override, this PR adds the ability for users to supply a custom batch template (for windows), by passing a `batch_template` argument to `Client.download_and_install_update()`.
The default template `WIN_BATCH_TEMPLATE` can be used as an example.
The following default variables are available for use in the custom template, but they can also be omitted: 
- `{log_lines}`  inserts lines that cause batch file output to be logged to file
- `{src_dir}`  inserts path to source directory
- `{dst_dir}` inserts path to destination directory
- `{robocopy_options}`  inserts robocopy options (default or custom)
- `{delete_self}` inserts a line that causes the batch file to delete itself (should only be used at end of file)
The user can also …
> Fix issue 47: enable custom batch templates

- requirements.txt
- setup.cfg
bump cryptography version to fix OpenSSL security issue
https://cryptography.io/en/latest/changelog/#v38-0-3
> sec1: bump cryptography version to 38.0.3

- src/tufup/client.py
remove target meta details from debug log messages, only show object count
> sec2: clean up client log messages

- src/tufup/repo/__init__.py
- src/tufup/repo/cli.py
- tests/test_repo.py
- tests/test_repo_cli.py
Patch creation can be time consuming. In some workflows, this is not desired. See e.g. #67.
For this reason, allowing users to skip patch creation sounds reasonable.
The following changes are made on the repo side:
- `Repository.add_bundle()` gets a `skip_patch` argument, which defaults to `False`
- the CLI command `tufup targets add` gets a `--skip-patch` (`-s`) option
The tufup `Client` should already know how to handle missing patches.
> Make patches optional

- pyproject.toml
- src/tufup/client.py
- src/tufup/repo/__init__.py
- tests/test_client.py
> adapt to changes in python-tuf v2.1.0 and v3.0.0

- README.md
- examples/client/example_app.py
- src/tufup/common.py
- tests/test_common.py
> explicitly warn against whitespace in app name and filename

- src/tufup/repo/__init__.py
- src/tufup/utils/platform_specific.py
- tests/test_repo.py
Use relative paths (i.e. relative to current working directory) for `repo_dir` and `keys_dir` in config file, if possible.
The config file itself is also in cwd.
Fixes #50
> Fix issue 50: use relative paths in config file

- src/tufup/utils/platform_specific.py
- tests/test_utils_platform_specific.py
The optional `process_creation_flags` argument allows users to override the [process creation flags][2] used for the subprocess call that runs the windows batch script that does the actual installation (i.e. moving files into place). 
The `process_creation_flags` argument accepts [subprocess Windows constants][1].
The default value remains `subprocess.CREATE_NEW_CONSOLE`, as before.
Usage example: 
```python
client.download_and_apply_update(..., process_creation_flags=subprocess.CREATE_NO_WINDOW)
```
fixes #81
[1]: https://docs.python.org/3/library/subprocess.html#windows-constants
[2]: https://learn.microsoft.com/en-us/windows/win32/procthread/process-creation-flags
> add optional process_creation_flags argument to _install_update_win()

- src/tufup/client.py
- src/tufup/utils/platform_specific.py
- tests/test_client.py
If a patch fails, for whatever reason, the downloaded patch file is flagged with a `.failed` suffix.
The client then continues without updating.
On the next run, the failed patch will be ignored, and a full update is downloaded instead.
fixes #98
> Fail-safe mechanism for patch updates

- src/tufup/repo/__init__.py
- tests/test_repo.py
- `Keys.find_private_key()` is now recursive, i.e. it searches subdirectories as well
- `Repository.initialize()` has an optional `extra_key_dirs` argument
fixes #102
> Improved key-finding ability for Repository.initialize

- examples/repo/repo_workflow_example.py
- src/tufup/repo/__init__.py
- tests/data/keystore/offline_secrets_1/root
- tests/data/keystore/offline_secrets_1/targets
- tests/data/keystore/offline_secrets_2/root_three
- tests/data/keystore/offline_secrets_2/root_three.pub
- tests/data/keystore/offline_secrets_2/root_two
- tests/data/keystore/online_secrets/snapshot
- tests/data/keystore/online_secrets/timestamp
- tests/data/keystore/root.pub
- tests/data/keystore/root_two.pub
- tests/data/keystore/snapshot.pub
- tests/data/keystore/targets.pub
- tests/data/keystore/timestamp.pub
- tests/data/repository/metadata/1.root.json
- tests/data/repository/metadata/2.root.json
- tests/data/repository/metadata/root.json
- tests/data/repository/metadata/snapshot.json
- tests/data/repository/metadata/targets.json
- tests/data/repository/metadata/timestamp.json
- tests/test_client.py
- tests/test_repo.py
Custom metadata as [described in the TUF spec][1] can be specified when adding a new bundle to a repository.
The high-level interface has been simplified slightly w.r.t. #100: users can now only add custom metadata to the *archive*, not to the patch (if any).
This makes sense, because the *archive* is the only thing a typical user should be interested in (patches are considered an internal implementation detail). If *really* necessary, the low-level `Roles.add_or_update_target()` can still be used to add custom metadata to *patches*.
On the repo side:
```python
...
repo.add_bundle(
new_version='2.3.4',
new_bundle_dir='dist/myapp',
custom_metadata=dict(foo='bar'),  # optional
)
...
```
The custom metadata ends up in the `targets.json` file as follows:
```json
{
"signatures": [
"..."
], …
```
> Simplified interface for custom metadata

- src/tufup/client.py
- tests/test_client.py
Invalid values for the `pre` argument are simply ignored in `Client.check_for_updates()`, as if no `pre` value were specified. 
To alert the user (dev), we do log a warning.
fixes #120
> ignore invalid pre-release specifiers when checking for updates

- src/tufup/repo/__init__.py
- src/tufup/repo/cli.py
- tests/test_repo_cli.py
Command line option for custom metadata.
Value must be  a JSON object.
For example:
`tufup targets add ... --meta '{"changes": ["item 1", "item 2"]}' ...`
fixes #112
> Add CLI option for custom metadata

- pyproject.toml
- src/tufup/client.py
The public API changes in [python-tuf v4.0.0][1] do not seem to affect us, but  theupdateframework/python-tuf@cb9aa4a does affect our client, due to my ill-fated choice to use the *private* `ngclient.Updater._trusted_set`.
fixes #133
related to secure-systems-lab/securesystemslib#767
[1]: https://github.com/theupdateframework/python-tuf/releases/tag/v4.0.0
> Upgrade tuf dependency to 4.0

- src/tufup/repo/__init__.py
- src/tufup/utils/platform_specific.py
- tests/test_utils_platform_specific.py
On macOS, it may be necessary, as in #145, to enable `symlinks` when files are moved into the `app_install_dir` using `shutil.copytree()`.
From the `shutil.copytree` [docs][1]:
>If symlinks is true, symbolic links in the source tree are represented as symbolic links in the new tree and the metadata of the original links will be copied as far as the platform allows; if false or omitted, the contents and metadata of the linked files are copied to the new tree.
This PR exposes the `symlinks` argument so user can enable this behavior as follows:
```python
client.download_and_apply_updates(..., symlinks=True)
```
If not specified, the *default* setting from `shutil.copytree` is used, i.e. `symlinks=False`.
fixes #145
[1]: https://docs.python.org/3/library/shutil.html#shutil.copytree
> Expose symlinks option for updates on macOS

- .github/workflows/publish.yml
- .github/workflows/test.yml
> split github workflows into test.yml and publish.yml

- .github/workflows/test.yml
- pyproject.toml
- dropped support for python 3.8
- added python 3.13 to test matrix
dropping support could be considered a backward incompatible change, but we require python>=3.9, so users running 3.8 simply cannot  install the new version of tufup
fixes #106
> drop support for python 3.8

- .github/workflows/test.yml
- examples/client/example_app.py
- examples/repo/repo_workflow_example.py
- src/tufup/__init__.py
- src/tufup/client.py
- src/tufup/common.py
- src/tufup/repo/__init__.py
- src/tufup/repo/cli.py
- tests/test_common_.py
- tests/test_repo.py
- tests/test_repo_cli.py
As explained in #154, `bsdiff4` may not always be the best option for patch creation.
As a workaround for users experiencing issues with `bsdiff4`, we now allow the use of alternative binary differencing solutions.
Users can subclass the abstract `BinaryDiff` (or the `DefaultBinaryDiff` implementation), and pass their subclass into the `Repository` and/or `Client` initializers using the *optional* `binary_diff` argument.
```python
class CustomBinaryDiff(BinaryDiff):
@staticmethod
def diff(*, src_bytes: bytes, dst_bytes: bytes) -> bytes:
my_diff = ...
return my_diff
@staticmethod
def patch(*, src_bytes: bytes, patch_bytes: bytes) -> bytes:
my_patched = ...
return my_patched
```
and then 
```python
repo = Repository(..., binary_diff=CustomBinaryDiff)
```
and/or
```python
client = …
```
> Customizable binary diff for patch creation
